language: node_js
node_js:
  - stable
  - lts/*

install:
  - npm install

script: skip # skip default test script which would run in watch mode

jobs:
  include:
    - stage: test plus coverage
      script: npm run coverage
      after_script:
        - COVERALLS_REPO_TOKEN=$coveralls_repo_token npm run coveralls
    - stage: bundle build plus size check
      script: npm run build
      after_script:
        - bundlesize
    - stage: publish package
      if: tag IS present
      script: npm run build
      after_script:
        - npm run cleanupminified
        - npm run copydistfiles
      before_deploy:
        - cd dist
      deploy:
        provider: npm
        email: $NPM_AUTH_EMAIL
        api_key: $NPM_AUTH_TOKEN
        skip_cleanup: true
        on:
          tags: true
          branch: master