name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  setup:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 17.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Cache Yarn
      uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-yarn-${{matrix.node-version}}-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-${{matrix.node-version}}-
          ${{ runner.os }}-yarn-
          ${{ runner.os }}-
    - name: Install Dependencies using Yarn
      run: yarn install --ignore-engines && git checkout yarn.lock
    - name: Install Dependencies using Yarn
      run: yarn install

  test-plus-coverage:
    needs: setup
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 17.x]

    steps:
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Cache Yarn
      uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-yarn-${{matrix.node-version}}-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-${{matrix.node-version}}-
          ${{ runner.os }}-yarn-
          ${{ runner.os }}-
    - name: Install Dependencies using Yarn
      run: yarn install --ignore-engines && git checkout yarn.lock
    - name: Run tests plus coverage
      run: yarn coverage
    - name: Track coverage
      run: yarn coveralls

  build-plus-sizecheck:
    needs: setup
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 17.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Cache Yarn
      uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-yarn-${{matrix.node-version}}-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-${{matrix.node-version}}-
          ${{ runner.os }}-yarn-
          ${{ runner.os }}-
    - name: Install Dependencies using Yarn
      run: yarn install --ignore-engines && git checkout yarn.lock
    - name: Build package
      run: yarn build
    - name: Check bundle-size
      run: yarn bundlesize
