name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  seetup:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 17.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Cache Yarn
      uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-yarn-${{matrix.node-version}}-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-${{matrix.node-version}}-
          ${{ runner.os }}-yarn-
          ${{ runner.os }}-
    - name: Install Dependencies using Yarn
      run: yarn install --ignore-engines && git checkout yarn.lock
    - name: Install Dependencies using Yarn
      run: yarn install

  test-plus-coverage:
    needs: setup
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 17.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Cache Yarn
      uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-yarn-${{matrix.node-version}}-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-${{matrix.node-version}}-
          ${{ runner.os }}-yarn-
          ${{ runner.os }}-
    - name: Install Dependencies using Yarn
      run: yarn install --ignore-engines && git checkout yarn.lock
    - run: yarn coverage

  build-plus-sizecheck:
    needs: setup
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 17.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Cache Yarn
      uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-yarn-${{matrix.node-version}}-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-${{matrix.node-version}}-
          ${{ runner.os }}-yarn-
          ${{ runner.os }}-
    - name: Install Dependencies using Yarn
      run: yarn install --ignore-engines && git checkout yarn.lock
    - name: Build package
      run: yarn build
    - name: Check bundle-size
      run: yarn bundlesize
