name: Publish

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Use Node 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        registry-url: https://registry.npmjs.org/
    - name: Install fresh dependencies
      run: yarn install --ignore-engines --frozen-lockfile
    - name: Run tests
      run: yarn testonly
    - name: Build bundle
      run: yarn build
    - name: Cleanup minified
      run: yarn cleanupminified
    - name: Copy additional 'dist' files
      run: yarn copydistfiles
    - name: Publish package
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      run: cd dist && npm publish
